add_subdirectory(test_buffer_view)
add_subdirectory(test_buffer)
add_subdirectory(test_logger)
add_subdirectory(test_batch)
add_subdirectory(test_paths)
add_subdirectory(test_ini_parser)
add_subdirectory(test_config)
add_subdirectory(test_engine)
add_subdirectory(test_task_types)
add_subdirectory(test_batch_result)
add_subdirectory(test_model_registry)
add_subdirectory(test_memory_pool)
add_subdirectory(test_kernels)
add_subdirectory(test_renderer)
add_subdirectory(test_datasource)
add_subdirectory(test_bounded_queue)
add_subdirectory(test_pipeline)
add_subdirectory(test_yolov4)
add_subdirectory(test_yolov5)
add_subdirectory(test_yolov6)
add_subdirectory(test_yolov7)
add_subdirectory(test_yolov8)
add_subdirectory(test_yolox)
add_subdirectory(test_yolor)
