# =============================================================================
#  trt_alpha :: YOLOv8 配置
# =============================================================================

[model]
engine = D:/ThirdParty/TensorRT-10.16.1.11/bin/yolov8n.trt
class_names_file = data/classes/coco80.txt
input_output_names = images,output0
batch_size = 1

[input]
dst_h = 640
dst_w = 640

[postprocess]
num_class = 80
conf_thresh = 0.25
iou_thresh = 0.45
top_k = 300